apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limit-range
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 1000m
      memory: 1Gi
    type: Container
---
apiVersion: v1
kind: Namespace
metadata:
  name: applications
