- name: get shared secrets
  include_vars:
    file: shared_vars/kubectl_secrets.yaml
    name: shared_secrets

- name: get {{ current_env }} secrets
  include_vars:
    file: env_vars/{{ current_env }}/kubectl/secrets.yaml
    name: env_secrets

- name: render secrets
  vars:
    combined_secrets: "{{ shared_secrets | combine(env_secrets, recursive=True) }}"
  template:
    src: templates/secrets.yaml.j2
    dest: /tmp/secrets.yaml
    mode: 0600

- name: apply secrets
  command: kubectl apply --validate --dry-run -f /tmp/secrets.yaml

- name: remove rendered secrets
  file: path=/tmp/secrets.yaml state=absent
